### ISSUE TITLE
Just something you might want to know

### ISSUE THREAD

**Issue by SteveLTN** [ndesilets/i-hate-remnant-decryption#1]
I encountered this incredibly hard puzzle:

```
40302
00000
00000
00000
02010
```

Worked half an hour on it by myself. Too much guess, I went to github before trying to to write my own. Found your project. Input the number, guess what, I waited for 5 minutes, didn't even print 
`xxx solutions generated in xxx seconds.`

I worked out the ones that I can be sure of, but then it's:

```
11943936 solutions generated in 5.36218810081 seconds.
```

Well, I gave up waiting eventually.

I figured, I can narrow the range down by making some guesses. So I guessed a value, and worked out the determined ones given my assumption. A Lot faster! Took only seconds!  But unfortunately no solutions are correct. Then I tried some other guesses, I got a solution in seconds.

This shows that we can improve the algorithm by start "guessing" the ones with lowest available options. Then maybe, use recursion, to iterate with our new known values.

Phew, what a hard one....

**Comment by ndesilets** [comment]
Ah, this seems to be one of those cases where it's generating too many potential candidates due to too few constraints from the input grid. Each additional constraint added will cut down the amount of potential candidates by a lot.

When I wrote this the 5x5 shape constraints were an afterthought (I wasn't familiar with Sudoku) and so I only implemented the shape constraints in find_solution() later on. Ideally I think these shape constraints should be considered when first generating the potential solutions in find_constraints(). This should cut down the amount of candidates significantly and reduce the overall runtimes.

Unfortunately... I beat the game a while ago and lost interest in this project :P. As a CS student, I still feel kind of feel dirty for not implementing a greedy algorithm of some sort and instead doing it the lazy way by brute forcing. But hey, it's a question of "how much effort do you _really_ want to put into this?" especially when the solutions are available online lol. Feel free to make a pull request if you'd like.

**Comment by SteveLTN** [comment]
Ah, that was just some rant. Happy gaming!
